#!/usr/bin/env python

import subprocess
import re
import time

# Glob pattern ensures that only tags which start with 'v[some digit]'
# are used
git_describe = subprocess.check_output(
    ['git', 'describe', '--match', 'v[0-9]*', '--long']).rstrip()
print "Git desribed current state as:", git_describe

match = re.match(
    'v([0-9]+)\.([0-9]+)-([0-9]+)-(g[a-fA-F0-9]+)',
    git_describe)

assert match
major = match.group(1)
minor = match.group(2)
commits_past_tag = match.group(3)
commit_id = match.group(4)

output_name = 'version.h'
guard_name = output_name.upper().replace('.', '_') + '_'
script_name = __file__
date_time = time.strftime("%Y-%m-%d %H:%M:%S")

output = """
/* THIS FILE WAS GENERATED BY {script_name} AT {date_time} */
#ifndef {guard_name}
#define {guard_name}

#define VERSION_MAJOR {major}
#define VERSION_MINOR {minor}
#define VERSION_COMMITS_PAST_TAG {commits_past_tag}
#define VERSION_COMMIT_ID "{commit_id}"

#ifdef Debug
#define VERSION_STRING "{git_describe}-DEBUG"
#else
#define VERSION_STRING "{git_describe}"
#endif

extern const char *g_version_string;

#endif /* {guard_name} */
""".format(**locals())

f = open(output_name, 'w')
f.write(output)
f.close()
